"""C2: deterministic scripted runs, offline and through the live session.

The real default_demo is 8,760 hourly ticks (~3 minutes), so the run tests use
a 30-day copy of it with the same four events squeezed into days 5-20.

Run from `simulation/`:
    .venv/bin/python -m pytest tests/test_scripted_run.py -q
"""

import csv
import hashlib
import json
from datetime import datetime, timedelta

import pytest
from starlette.testclient import TestClient

from sandbox import constants
from sandbox.runner import run_script_offline
from sandbox.script import SCENARIO_DIR, load_script, parse_script
from sandbox.server import app, get_session
from sandbox.session import SessionConfig, SimulationSession

SHORT_DAYS = {"crack": 5, "tilt": 12, "vibration": 15, "cave_in": 20}


def _short_script():
    raw = json.loads((SCENARIO_DIR / "default_demo.json").read_text())
    raw["name"] = "short_demo"
    raw["duration_days"] = 30
    for ev in raw["events"]:
        ev["day"] = SHORT_DAYS[ev["type"]]
    return parse_script(raw)


@pytest.fixture(scope="module")
def two_runs(tmp_path_factory):
    script = _short_script()
    root = tmp_path_factory.mktemp("scripted")
    return script, run_script_offline(script, root / "a"), run_script_offline(script, root / "b"), root


def _rows(path):
    with open(path, newline="") as fh:
        return list(csv.DictReader(fh))


def _t(iso):
    return datetime.fromisoformat(iso.replace("Z", "+00:00"))


def test_offline_twice_gives_identical_files(two_runs):
    _, a, b, root = two_runs
    assert a == b
    for name, digest in a.items():
        assert digest == hashlib.sha256((root / "a" / name).read_bytes()).hexdigest()
        print(f"sha256 {name} {digest}")


def test_offline_output_shape(two_runs):
    script, _, _, root = two_runs
    lines = (root / "a" / "nodes.csv").read_text().splitlines()
    assert lines[0].startswith("# GENERATED BY SIMULATOR")
    assert f"scenario={script.name} seed={script.seed}" in lines[0]
    assert len(lines) == 2 + script.n_ticks * 31
    assert lines[2].startswith("2026-01-01T00:00:00Z,")
    assert lines[-1].startswith("2026-01-30T23:00:00Z,")


def test_each_event_fires_once_on_its_day(two_runs):
    script, _, _, root = two_runs
    rows = [r for r in _rows(root / "a" / "events.csv") if r["kind"] != "zone_transition"]
    base = _t(script.base_iso_time)
    fired = {r["kind"]: r for r in rows if r["kind"] in ("crack", "tilt", "blast", "collapse")}
    assert sorted(fired) == ["blast", "collapse", "crack", "tilt"]
    assert sum(r["kind"] in fired for r in rows) == 4
    for kind, ev in zip(("crack", "tilt", "blast", "collapse"), script.events):
        assert _t(fired[kind]["t_iso"]) == base + timedelta(days=ev["day"])


def test_first_alarm_of_each_ring_event_lands_within_one_packet(two_runs):
    script, _, _, root = two_runs
    rows = _rows(root / "a" / "events.csv")
    alarms = [r for r in rows if r["kind"] == "node_alarm"]
    base = _t(script.base_iso_time)
    for kind, ev in (("crack", script.events[0]), ("collapse", script.events[3])):
        at = base + timedelta(days=ev["day"])
        first = min((_t(a["t_iso"]) for a in alarms if _t(a["t_iso"]) >= at), default=None)
        assert first is not None, f"no alarm after the {kind}"
        assert timedelta(0) <= first - at <= timedelta(seconds=script.tick_seconds), (kind, first - at)
    notes = {a["note"].split()[1] for a in alarms}
    assert notes == {"WARNING", "CRITICAL"}


def test_tilt_alarms_come_from_the_tilt_not_a_ring(two_runs):
    script, _, _, root = two_runs
    base = _t(script.base_iso_time)
    start, end = (base + timedelta(days=d) for d in (12, 20))
    alarms = [r for r in _rows(root / "a" / "events.csv")
              if r["kind"] == "node_alarm" and start <= _t(r["t_iso"]) < end]
    assert alarms and all(a["note"].endswith("WARNING") for a in alarms)


def test_packets_follow_the_script_tick(tmp_path):
    script = _short_script()
    s = SimulationSession(SessionConfig(out_dir=tmp_path, save_packet_json=False))
    s.mqtt_bridge.enabled = False
    s.load_script(script)
    assert s.packet_aggregator.session_id == "short_demo"
    s.start()
    ids = []
    for _ in range(3):
        payload = s.tick()
        assert payload["packet_available"]
        ids.append(s.last_finalized_packet["end_sim_time"] - s.last_finalized_packet["start_sim_time"])
    s.stop()
    assert ids == [script.tick_seconds] * 3


def test_load_script_refused_while_running_and_reset_unloads(tmp_path):
    s = SimulationSession(SessionConfig(out_dir=tmp_path, save_packet_json=False, seed=7))
    s.mqtt_bridge.enabled = False
    s.start()
    with pytest.raises(RuntimeError, match="running"):
        s.load_script(_short_script())
    s.stop()
    s.load_script(_short_script())
    assert s.config.seed == 20260927 and s.config.auto_snap_speed is False
    assert len(s._pending_script_events) == 4
    s.reset()
    assert s.script is None and s._pending_script_events == []
    assert (s.config.seed, s.config.tick_duration_sim_s) == (7, constants.TICK_SIM_SECONDS)
    assert s.packet_aggregator.window_duration_sim_s == constants.TICK_SIM_SECONDS


# ---------------------------------------------------------------------------
# POST /script/run
# ---------------------------------------------------------------------------


@pytest.fixture
def live():
    session = get_session()
    session.reset()
    session.mqtt_bridge.enabled = False
    with TestClient(app) as client:
        yield client, session
    session.reset()


def test_script_run_loads_the_live_session(live):
    client, session = live
    res = client.post("/script/run", json={"name": "default_demo"})
    assert res.status_code == 200
    body = res.json()
    assert (body["status"], body["name"], body["n_ticks"]) == ("loaded", "default_demo", 8760)
    assert [e["type"] for e in body["events"]] == ["crack", "tilt", "vibration", "cave_in"]
    assert session.script is not None and not session.is_running
    assert session.speed_multiplier == pytest.approx(body["speed"])


def test_script_run_refused_while_running(live):
    client, session = live
    session.start()
    res = client.post("/script/run", json={"name": "default_demo"})
    assert res.status_code == 409
    assert session.script is None
    session.stop()


def test_script_run_unknown_and_invalid(live, tmp_path):
    client, _ = live
    assert client.post("/script/run", json={"name": "nope"}).status_code == 404
    assert client.post("/script/run", json={"name": "../etc/passwd"}).status_code == 404


def test_interventions_and_forge_seed_show_events_not_pieces(live, monkeypatch):
    client, session = live
    client.post("/script/run", json={"name": "default_demo"})
    session._fire_due_script_events(61.0)
    session._fire_due_script_events(121.0)
    data = client.get("/interventions").json()
    owners = [f["script_event"] for f in data["pillar_failures"]]
    assert set(owners) == {0, 1} and owners.count(1) == 1 and owners.count(0) > 10
    assert set(data["script_events"]) == {"0", "1"}

    import forge.server as forge_server

    class _Resp:
        status = 200
        def __enter__(self): return self
        def __exit__(self, *a): return False
        def read(self): return json.dumps({**data, "t_sim_seconds": 121 * 86400.0}).encode()

    monkeypatch.setattr(forge_server.urllib.request, "urlopen", lambda *a, **k: _Resp())
    seeded = TestClient(forge_server.app).get("/forge/seed").json()
    assert [e["type"] for e in seeded["events"]] == ["crack", "tilt"]
    assert all(e["source"] == "live" for e in seeded["events"])
    frame = TestClient(forge_server.app).post(
        "/forge/frame", json={"day": 130.0, "events": seeded["events"]}
    )
    assert frame.status_code == 200


def test_script_done_once_the_clock_reaches_the_duration(tmp_path):
    raw = json.loads((SCENARIO_DIR / "default_demo.json").read_text())
    raw.update(name="one_day", duration_days=1, tick_seconds=43200, events=[])
    script = parse_script(raw)
    s = SimulationSession(SessionConfig(out_dir=tmp_path, save_packet_json=False))
    s.mqtt_bridge.enabled = False
    assert not s.script_done
    s.load_script(script)
    s.start()
    s.tick()
    assert not s.script_done
    s.tick()
    assert s.script_done and script.n_ticks == 2
    s.stop()
    assert s.script_done  # still true after stop: /health reports it


def test_ws_set_speed_is_ignored_while_a_script_is_loaded(live):
    """The 3D client sends its fixed 10x on every connect; a script's speed must survive it."""
    client, session = live
    body = client.post("/script/run", json={"name": "default_demo"}).json()
    with client.websocket_connect("/ws") as ws:
        assert ws.receive_json()["type"] == "init"
        ws.send_json({"action": "set_speed", "multiplier": 10})
        ws.send_json({"action": "set_speed", "multiplier": 10})
        # a round trip after the two set_speed frames proves they were processed
        ws.send_json({"action": "nonsense"})
        while ws.receive_json().get("type") != "error":
            pass
    assert session.speed_multiplier == pytest.approx(body["speed"])
    # HTTP /control, the demo runner's route, still sets it
    assert client.post("/control", json={"action": "set_speed", "multiplier": 5000}).status_code == 200
    assert session.speed_multiplier == 5000
    # and without a script the WS still steers the clock
    session.reset()
    with client.websocket_connect("/ws") as ws:
        ws.receive_json()
        ws.send_json({"action": "set_speed", "multiplier": 25})
        ws.send_json({"action": "nonsense"})
        while ws.receive_json().get("type") != "error":
            pass
    assert session.speed_multiplier == 25
